spring:
  kafka:
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: survey-app-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    bootstrap-servers: localhost:9092
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
      httpclient:
        response-timeout: 5s
        max-header-size: '65536'
  application:
    name: survey-application
  codec:
    max-in-memory-size: 16MB
  r2dbc:
    password: postgres
    url: r2dbc:postgresql://localhost:5432/survey
    username: postgres
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: false
  flyway:
    enabled: false
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      FAIL_ON_IGNORED_PROPERTIES: false
      FAIL_ON_NULL_FOR_PRIMITIVES: false
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 10s
    socket-timeout: 30s
    username: 
    password: 
    rest:
      read-timeout: 30s
    data:
      client:
        reactive:
          max-in-memory-size: 100MB
          endpoints: localhost:9200

# Set to false to disable all Elasticsearch features
elasticsearch:
  enabled: false
    
springdoc:
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    urls[0]:
      url: /v3/api-docs
      name: Default

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  refresh:
    expiration: '604800000'
  expiration: '900000'

server:
  port: '8080'

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure: INFO
    org.springframework.web.reactive: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.data.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG
    org.springframework.r2dbc: DEBUG
    org.site.survey: DEBUG
    org.springframework.jdbc.core: DEBUG
    org.springframework.data.elasticsearch.client.WIRE: DEBUG