spring:
  config:
    import: optional:file:.env[.properties]
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
      httpclient:
        response-timeout: 5s
        max-header-size: '65536'
  main:
    banner-mode: off
  application:
    name: survey-application
  codec:
    max-in-memory-size: 16MB
  r2dbc:
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USERNAME}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: false
  flyway:
    enabled: false
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      FAIL_ON_IGNORED_PROPERTIES: false
      FAIL_ON_NULL_FOR_PRIMITIVES: false
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS}
    connection-timeout: 10s
    socket-timeout: 30s

elasticsearch:
  enabled: true
    
springdoc:
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    urls[0]:
      url: /v3/api-docs
      name: Default

jwt:
  secret: ${JWT_SECRET}
  refresh:
    expiration: '${JWT_REFRESH_EXPIRATION}'
  expiration: '${JWT_EXPIRATION}'

server:
  port: '8080'

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure: INFO
    org.springframework.web.reactive: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.data.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG
    org.springframework.r2dbc: DEBUG
    org.site.survey: DEBUG
    org.springframework.jdbc.core: DEBUG
    org.springframework.data.elasticsearch.client.WIRE: DEBUG