spring:
  kafka:
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: survey-app-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    bootstrap-servers: localhost:9092
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
      httpclient:
        response-timeout: 5s
        max-header-size: '65536'
  application:
    name: survey-application
  codec:
    max-in-memory-size: 16MB
  r2dbc:
    password: postgres
    url: r2dbc:postgresql://localhost:5432/survey
    username: postgres
springdoc:
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    urls[0]:
      url: /v3/api-docs
      name: Default

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  refresh:
    expiration: '604800000'
  expiration: '20000'
server:
  port: '8080'
